// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeniJa7vSXnJqRYKsFdiuvW5xzJfNHDIs',
    appId: '1:212082514288:web:e28534ca7ff850b302d7b5',
    messagingSenderId: '212082514288',
    projectId: 'true-connect-a6081',
    authDomain: 'true-connect-a6081.firebaseapp.com',
    storageBucket: 'true-connect-a6081.firebasestorage.app',
    measurementId: 'G-HTR3CJGESL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc9O0-Qw3kdcAT7yIVy6gHlXo3mVEBxTg',
    appId: '1:212082514288:android:64b739e9a6c61c7702d7b5',
    messagingSenderId: '212082514288',
    projectId: 'true-connect-a6081',
    storageBucket: 'true-connect-a6081.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZCB1h_KiPuawqXyOCTdc5w497JaOnh3U',
    appId: '1:212082514288:ios:0235dd4c0d8509b002d7b5',
    messagingSenderId: '212082514288',
    projectId: 'true-connect-a6081',
    storageBucket: 'true-connect-a6081.firebasestorage.app',
    iosBundleId: 'com.example.trueConnect',
  );
}
